### ISSUE TITLE
LiveQuery subscription to specific fields not working

### ISSUE THREAD

**Issue by ruiluo-mobile** [parse-community/ParseLiveQuery-iOS-OSX#111]
I try to only subscribe to some specific fields, but it seems that it doesn't work.

I have these simple swift code for subscription:
let query: PFQuery<PFObject> = PFQuery(className: "LiveQueryTestObject")
query.whereKey("objectId", equalTo: "o5OAoLXFRx")
query.selectKeys(["objectId", "description"])
subscription = liveQueryClient?.subscribe(query)

In the server log, I only see 'where' field, but no 'field' key:
2017-04-20T22:25:54.397673+00:00 app[web.1]: [36mverbose[39m: Request: {"requestId":1,"op":"subscribe","query":{"className":"LiveQueryTestObject","where":{"objectId":"o5OAoLXFRx"}}}

did anyone meet the same issue before?

**Comment by loxx123** [comment]
Yep, I'm having the same problem, it won't work with multiple "where" statements in the query, specifically on _User class.

**Comment by loxx123** [comment]
the only way around this for now is to intercept the event with a series of if/thens in the handlers and reject the events that don't match the query you tried to construct. This is a terrible way to handle this, but it's the only way I can find for now.

**Comment by loxx123** [comment]
@ruiluo-mobile in fact, here's what I'm doing, I would normally have the top query with a few more "where" commands, but it will only work with the one "where" command, so it receives all events from where:

`[self.combinedQuery whereKey:@"holderId" equalTo:self.holderId]`

the problem here is that the client does subscribe to the live query on the backend, but only ONE device can subscribe to the full query, I've tried with two devices and the first device that subscribes to the full query with multiple "where" statements, it works just fine, but when a new client subscribes to this same query after the first device already subscribed, then the query's additional "where" statements fail.

This system i have here for a chat system of one on one, live chatting, just like Apple's imessenger system, but it's one on one for each item in my app, so every macro item has a new one on one, live chat, meaning the "where" queries are crucial to make this work the right way. 

So the work around is this:

<img width="1143" alt="screen shot 2017-06-26 at 2 03 59 pm" src="https://user-images.githubusercontent.com/16133244/27558030-02d97844-5a79-11e7-843f-5c9cc4573a4e.png">


As you can see, in the "addCreateHandler", I have to filter out the additional users that may be speaking to the other user so this chat stays a one on one chat. I've tested this as well. This works to keep the chat one on one, but if i didn't have this return handler in the if/then statement, then i'd receive other PFObjects that match only on this:

`[self.combinedQuery whereKey:@"holderId" equalTo:self.holderId]`

I'm not sure if the fix here is a simple one being that multiple "where" queries will work with the first client that subscribes to the live query and the second subscriber is able to subscribe, but it will only subscribe to:

`[self.combinedQuery whereKey:@"holderId" equalTo:self.holderId]`

this problem seems deeper than just an iOS coding issue, and perhaps this is only the case when we're dealing with the _User class on the backend, I've not tried to recreate this with other non-lock downed classes yet.

More information:

here's what the query should look like, ideally:

```
        self.combinedQuery = [PFQuery queryWithClassName:@"Chats"];
	[self.combinedQuery includeKey:@"userId"];
	[self.combinedQuery includeKey:@"toUser"];
	[self.combinedQuery  whereKey:@"toUser" equalTo:[PFUser currentUser]];
	[self.combinedQuery  whereKey:@"userId" equalTo:self.incomingUser];
	[self.combinedQuery whereKey:@"holderid" equalTo:self.holderId];
```
this will only work with the first client that subscribes to this query

the second client, only this works
```
        self.combinedQuery = [PFQuery queryWithClassName:@"Chats"];
	[self.combinedQuery includeKey:@"userId"];
	[self.combinedQuery includeKey:@"toUser"];
	[self.combinedQuery whereKey:@"holderid" equalTo:self.holderId];
```

so it's literally stripping out this, but without me actually removing this from the code:
```
	[self.combinedQuery  whereKey:@"toUser" equalTo:[PFUser currentUser]];
	[self.combinedQuery  whereKey:@"userId" equalTo:self.incomingUser];
```

I keep the code the exactly the same as this:

```
        self.combinedQuery = [PFQuery queryWithClassName:@"Chats"];
	[self.combinedQuery includeKey:@"userId"];
	[self.combinedQuery includeKey:@"toUser"];
	[self.combinedQuery  whereKey:@"toUser" equalTo:[PFUser currentUser]];
	[self.combinedQuery  whereKey:@"userId" equalTo:self.incomingUser];
	[self.combinedQuery whereKey:@"holderid" equalTo:self.holderId];
```
but again, something on the backend or in the Swift Parse Live Query library wont' allow two subscriptions to the same sort of query. 

The workaround I linked in the image above works just fine, the only problem i have with that work around is its taxing on the backend, potentially, since it's sending back information to the client that I didn't ask for, also, it seems like this could be a security risk.

More information, I have in my Appdelegate this:

```
	PFACL *defaultACL = [PFACL ACL];
	[defaultACL setPublicReadAccess:YES];
	[defaultACL setPublicWriteAccess:YES];
	[PFACL setDefaultACL:defaultACL withAccessForCurrentUser:YES];
```

So I'm not using ACLs for anything but the standard Parse default classes, everything else is open for now while in production, so I doubt this is regular Parse object ACL problem, unless it is with the _User class, and in that case, I wouldn't know, I've not looked at the server side Parse code much at all. 

Also in my Appdelegate, I have this:

`		configuration.localDatastoreEnabled = YES;`

Perhaps this is a local storage issue? I don't know, I don't have a clue, but I've worked on this for a couple of hours until I just installed the carppy hack and gave up for now. 

Anyway, perhaps @flovilmart can take a look at this later, I know there's a bunch of crap that needs fixing right now, but perhaps this is a known issue given how simplistic the live query client is. I would hope that we can solve this sometime in the future, it would be nice to be able to run advanced queries including OR queries using Parse Live Query, but this would take a lot of work, I'm sure.

**Comment by flovilmart** [comment]
Yes, we don't provide (yet) a filter on the selectKeys but that's a nice feature request as it would indicate the server that some mutations are not to be forward to the client. 

Any one of you wanting to contribute that feature to the server? then it should automatically work on the client.
