### ISSUE TITLE
Query findObjectsInBackground outstanding network connection crash.

### ISSUE THREAD

**Issue by TulioOParreiras** [parse-community/ParseLiveQuery-iOS-OSX#157]
Hi, I am trying to observe a live query, but when I call the method findObjectsInBackground, the app crashes with the message: 'This query has an outstanding network connection. You have to wait until it's done.'

`class func observeTravel(travelId: String, completion: @escaping (Travel) -> Swift.Void) {
        let travelQuery = ServiceParse.travelQuery
        travelQuery.whereKey("objectId", equalTo: travelId)
        travelQuery.includeKey("driver")
        travelQuery.includeKey("passenger")
        travelQuery.includeKey("vehicle")
        travelQuery.includeKey("originAddress")
        travelQuery.includeKey("destinyAddress")
        travelQuery.findObjectsInBackground(block: { (travels, error) in
            if error == nil {
                completion(travels!.first!)
            }
        })
        ServiceParse.subscription = ServiceParse.liveQuery.subscribe(travelQuery).handle(Event.updated) { (_, travel) in
            completion(travel)
        }
    }`

Can anyone help me?

**Comment by flovilmart** [comment]
This is not an issue with LiveQuery but the parse SDK and more precisely with your code.

I'm not sure how ` let travelQuery = ServiceParse.travelQuery` returns a new query each time, but the error you see is because you're mutating an existing query or running the query twice before it completes.

Also, for non SDK related issues, but code or implementation issues, consider opening a post on stackoverflow.

**Comment by TulioOParreiras** [comment]
Ok, thank you for the feedback.
