### ISSUE TITLE
Error on project build

### ISSUE THREAD

**Issue by Eke** [parse-community/ParseLiveQuery-iOS-OSX#2]
Hello,
I get error when building app

Value of optional type 'ParseClientConfiguration?' not unwrapped; did you mean to use '!' or '?'?

Error is in Client.swift file on line 40.

Same errors are in same file on line 64, 65, 99, 100 and 101.

Can you please tell me , what is wrong?

**Comment by nlutsenko** [comment]
Hey @Eke, we would need to address that, since the API changed slightly with Parse 1.13.0.
One of 2 ways to go:
- Temporarily revert Parse to 1.12.0 until you see this issue closed and liv query client 1.0.1 released.
- Patch this in place by adding a question mark

Will send a pull request with a fix in a bit.

**Comment by Eke** [comment]
Hey @nlutsenko , thanks for reply.

At this moment i patched it manually. happy to hear about pull request.

You guys are doing great job, thanks for everything :+1:

**Comment by nlutsenko** [comment]
Just attached it - should fix all the issues. ;)

**Comment by otymartin** [comment]
@nlutsenko pod `ParseLiveQuery` is not giving me `version 1.0.1` even `pod 'ParseLiveQuery', '~> 1.0'` says

```
[!] Unable to satisfy the following requirements:

- `ParseLiveQuery (~> 1.0.1)` required by `Podfile`
```

**Comment by otymartin** [comment]
Figured it out via `pod update` nevermind :)

**Comment by nlutsenko** [comment]
:) Yup, we had a new version released with this fix.
