### ISSUE TITLE
Module updates needed to build under Carthage

### ISSUE THREAD

**Issue by bayareahank** [parse-community/ParseLiveQuery-iOS-OSX#206]
Current release would fail when building carthage, from the following two sources: 

Parse-iOS-sdk needs to be updated to 1.7.2, otherwise the build would fail at ParseFacebookUtilsV4-iOS.

Starscream needs to be updated to 3.0.6 or later (3.1.0 to support Swift 5). Otherwise swift code won't compile after Carthage build. See #159 

Workaround is to add these dependencies manually in your Cartfile , beyond ParseLiveQuery-iOS.

**Comment by TomWFox** [comment]
Would you be willing to make a PR with a fix?

**Comment by noobs2ninjas** [comment]
This is planned for release 1.7.0. The primary reason we haven't done this yet is because of issue #194. Once updated to Swift 5.0 the Travis build fails. Now, you'd think it would be as easy as updating the xcode version in the build files but apparently not. Really those files need to be rewritten for consistency because PLQ's build files are a mess and totally off from the other Parse repositories. Regardless, this would need to build in order to merge and deploy any sort of update that has dependencies that use Swift 5.0.

**Comment by noobs2ninjas** [comment]
@bayareahank speaking of which if you know anything about CircleCI or Travis we could definitely use help with that. I've been wanting to get us all up to date for months.

**Comment by TomWFox** [comment]
v2.7.0 should have addressed these issues.
