### ISSUE TITLE
What about using Apple's Network framework instead of Starscream?

### ISSUE THREAD

**Issue by ShawnBaek** [parse-community/ParseLiveQuery-iOS-OSX#221]
https://developer.apple.com/videos/play/wwdc2018/715/

In wwdc 19, socket was added to the network framework.

It's my opinion, but looking at the future seems to be a good choice.

**Comment by drdaz** [comment]
I had no idea Network.framework existed. Very cool!

**Comment by noobs2ninjas** [comment]
This is pretty cool. 

A lot of Apples new frameworks are much more developer friendly. Unfortunately, when they release these new frameworks, they only allow that year's iOS version and later. So, in order to use this instead of Starscream(other than a lot of work and time) it would raise our base from iOS 8 to iOS 12.  Now, I know Apple is much better than Android in terms of updating older devices. However, best practices are still to support as far back as possible.

**Comment by cbaker6** [comment]
Closing since this has been answered
