### ISSUE TITLE
Is there a framework for iOS Swift (or Objective C)?

### ISSUE THREAD

**Issue by taufiq-husain** [parse-community/ParseLiveQuery-iOS-OSX#5]
I'm using Swift as my primary language but I don't use cocoa pods. I was wondering if you could put up documentation on how to use Live Queries in my projects by using frameworks or some other way? Thanks.

**Comment by otymartin** [comment]
@taufiq-husain Hey I think you just download this package, then drop Parse LiveQuery folder in your project like so
<img width="267" alt="screen shot 2016-03-23 at 9 49 38 am" src="https://cloud.githubusercontent.com/assets/2222881/13987239/057cf12c-f0dd-11e5-862c-aa2fee85e385.png">

Then in your project, just call the subscribe method on a query object.
eg. `let subscribe = roomQuery.subscribe()` it should autocomplete. Someone verify my advice because I haven't tried to make the live query feature work yet.

<img width="451" alt="screen shot 2016-03-23 at 9 53 36 am" src="https://cloud.githubusercontent.com/assets/2222881/13987298/44f44184-f0dd-11e5-8d78-c5d3beea5109.png">

**Comment by nlutsenko** [comment]
You can also use `Carthage` to get the pre-built framework for your needs, which will compile the framework and it's just good to go.
I would advise against dropping the code in, since it could be very hard to upgrade at that point.

**Comment by cubycode** [comment]
> You can also use Carthage to get the pre-built framework for your needs, which will compile the framework and it's just good to go.
And how do I extract ParseLiveQuery framework with Carthage? I've tried putting `github "ParseLiveQuery"` in my Cartfile but the Terminal prints out an error after running `carthage update`
