### ISSUE TITLE
What's going on with this repo?

### ISSUE THREAD

**Issue by kajensen** [parse-community/ParseLiveQuery-iOS-OSX#58]
There are many things stopping this library from being useful let alone useable in production. I can see this being an incredibly useful addition to the parse framework but it is simply not ready yet. No support for pointers (pfgeopoints, dates), compound queries, multiple subscriptions.. to me are necessary at the bare minimum.

Is anyone taking the lead contributing to this? I'm happy to help but i'm not sure how to get started.

**Comment by kajensen** [comment]
I just submitted a pull request to allow "nearSphere" queries with pfgeopoints. https://github.com/ParsePlatform/ParseLiveQuery-iOS-OSX/pull/59 Its probably not the optimal solution, but it works.

I'm sure we can do something similar in regards to https://github.com/ParsePlatform/ParseLiveQuery-iOS-OSX/issues/47 but i'd like some feedback first with someone more familiar with the repo.

**Comment by richardjrossiii** [comment]
When I initially built this prototype (which is really what this repo was, unfortunately, a prototype built in 3 days during a hackathon) - its release was somewhat rushed due to the shutdown announcement. 

Due to this reason, a lot of the things you mention are not currently implemented client-side (but AFAIK, they're mostly implemented server-side correctly). The big blocker at the time of release (and still, currently) was the lack of an API for encoding a PFQuery in the iOS SDK. Initially, we had plans to ship such an API in the core SDK, but unfortunately we did not have the time to finalize that. (Sidenote, an even longer-term plan was to merge live-queries back into the core SDK, similar to how they ship for Javascript) 

Actively, this repository is not being maintained. I will review pull-requests as they come in periodically, and it would be awesome to see the community pick it up. I honestly think the best approach would be to have a public API for PFQuery in the main SDK to support encoding.

**Comment by Samigos** [comment]
@richardjrossiii First of all, I thank the whole Parse team for the amazing job!!!
Secondly, are any of these issues going to be solved, or the LiveQuery SDK development has been stopped?

Thanks in advance!
