### ISSUE TITLE
parseObject method can't parse complex PFObjects

### ISSUE THREAD

**Issue by agordeev** [parse-community/ParseLiveQuery-iOS-OSX#64]
Hi @richardjrossiii , is it possible to improve `parseObject<T: PFObject>(objectDictionary: [String:AnyObject])` method, so it correctly parses complex `PFObject`s? Currently it even leaves `PFACL` as a plain dictionary, which causes an error on saving the object later (`[NSCFDictionary hasUnresolvedUser] unrecognized selector sent to instance`)

I was thinking of using `(instancetype)ACLWithDictionary:(NSDictionary *)dictionary` method, but it seems marked as a private. 

Is there a way to use a standard Parse iOS SDK for parsing the server's response to `PFObject`?

**Comment by richardjrossiii** [comment]
The initial plan was to make `PFEncoder`/`PFDecoder` from the core SDK public classes, and if you were to publicize the headers for that (or port that logic to swift), you probably could make that work.

Other than that, there's no methods on `PFObject` that I'm aware of (private or otherwise) that allow you to construct it from it's REST representation.
