### ISSUE TITLE
Client().subscribe never calls handleSubscribe

### ISSUE THREAD

**Issue by DoneStuffGetting** [parse-community/ParseLiveQuery-iOS-OSX#8]
Using PFQuery().subscribe works fine but handleSubscribe is never called when using Client().subscribe. Server is v2.2.0 as v2.2.1 breaks [https://github.com/ParsePlatform/parse-server/issues/1147](https://github.com/ParsePlatform/parse-server/issues/1147)

**Comment by nlutsenko** [comment]
`handleSubscribe` wouldn't  be called. It's the method for you to register a subscription handler.
Any chance you can paste a code sample?

**Comment by DoneStuffGetting** [comment]
```
let query2sub = PFQuery(className: "yolo").whereKey("sup", greaterThanOrEqualTo: 10)

let subscrip = query2sub.subscribe()

subscrip.handleSubscribe { _ in
     print("connected!!")
     subscrip.handle(Event.Created) { _, obj in
          print(obj)
     }
}
```

Above works, but if I put the ".handle(Event.Created){}" right after "subscribe", it doesn't quite work. There's a delay between calling subscribe() and receiving the subscription object back, such that if I call handle() right after subscribe(), it doesn't quite register(?). Something along the lines of subscribe() == asynchronous and handle() trying to hook up too early.

But that aside, the problem I'm having is with Client() in any init form. It simply does not work with or without the handleSubscribe() or the handle() call. For instance, this doesn't work at all:

```
let client = Client() ~OR~ Client(server: "...", applicationId: "...", clientKey: "...")
let query = PFQuery(className: "yolo")
let sub = client.subscribe(query)
```

And then slap the handle()'s after this, and still nothing works.

**Comment by nlutsenko** [comment]
It registers the subscription regardless, though it's not synchronous, meaning subscribe schedules the subscription to be registered with the server, even if it's connected to the server. All the handlers are registered on it in the manner that they will be called when the event is sent back to the client regardless of when they are registered before it finishes or after.

Regarding the `Client()` piece - not sure why it doesn't work for you explicitly here - any chance you can register the error handler aka `handleError()` to see if there are any errors coming your way?
The only difference between custom `Client()` and the built-in `query.subscribe()` is that we create the built-in client for you.

**Comment by richardjrossiii** [comment]
As for not receiving any events, It's most likely because we store the `Subscription` weakly inside the `Client`, to prevent zombie subscriptions that last forever. To continue receiving events for a Subscription,  you must hold onto a strong reference to it yourself (as an instance variable on your view controller, for example).

**Comment by nlutsenko** [comment]
@skimgosu, I think I know why this happens for you.
The object that you get back from `query.subscribe()` is required to be stored by you with a strong reference, otherwise - it is going to be unsubscribed automatically. This is done to ensure that there are no leftovers and we don't keep references on things more than we should, thus don't retain your view controller for example even if you don't unsubscribe explicitly.

The fix would be pretty trivial - store the strong reference to both Client and Subscription objects that you are referencing as properties on any object instance.

**Comment by nlutsenko** [comment]
@richardjrossiii Race condition, ftw! :grin: 

@skimgosu Since the fix sounds trivial and on your side, I am going to close down this issue.
Please let us know if there is something else that we missed or if there is anything we can help you with.
