### ISSUE TITLE
Can't run ParseLiveQuery built via Carthage

### ISSUE THREAD

**Issue by JoeSzymanski** [parse-community/ParseLiveQuery-iOS-OSX#84]
I'm trying to do some testing of ParseLiveQuery, and I'm running into a problem integrating the framework in Xcode 8.

I'm using Carthage with ParseLiveQuery as the only dependency. ParseLiveQuery and the necessary dependencies appear to be built, and I can properly add them to my Xcode project and build. The problem occurs when I try to run the app. The app crashes immediately with the following error:

`dyld: Library not loaded: @rpath/BoltsSwift.framework/BoltsSwift
  Referenced from: /Users/jszymanski/Library/Developer/CoreSimulator/Devices/66A77A5B-1C69-49FF-A3E8-887858A83CE5/data/Containers/Bundle/Application/10078C94-A621-4A5C-ADAA-6A1D5A2DDF0B/ParseTest.app/Frameworks/ParseLiveQuery.framework/ParseLiveQuery
  Reason: Incompatible library version: ParseLiveQuery requires version 1.0.0 or later, but BoltsSwift provides version 0.0.0`

Does anyone have any idea how to get around this problem? I've tried manually integrating everything, but that has had all sorts of other problems. I'm trying to avoid going down the route of CocoaPods, due to how much additional overhead there is in place to get that built and working.

**Comment by flovilmart** [comment]
I've noticed that issue too, I'm not sure how to fix it.

**Comment by JoeSzymanski** [comment]
I have been digging, and I think the problem here is that ParseLiveQuery looks like it uses mostly pre-built binaries (where possible), and somehow, those have a dyld version and dyld compatibility version of 0, while the ParseLiveQuery binary somehow expects those to have versions of at least 1.

I've tried changing the carthage command to force everything to be built from source, and that results in build errors in one of the phases that should only be used for CocoaPods:

> The following build commands failed:
>     PhaseScriptExecution [CP]\ Check\ Pods\ Manifest.lock /Users/jszymanski/Library/Developer/Xcode/DerivedData/ParseLiveQuery-ffrsytiiiarwbxgwnnhibvzrnwuh/Build/Intermediates/ParseLiveQuery.build/Release-iphoneos/ParseLiveQuery-iOS.build/Script-12BD489D413AD268FF85A8FA.sh
> error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.

On top of this, I didn't think it was possible to ship binaries of Swift frameworks, which seems to run counter to the fact that this: https://forums.developer.apple.com/thread/66852
It looks like this repo should remove the binary artifacts for the framework to avoid running into problems like this, then figure out how to fix the build when running via Carthage.

**Comment by JoeSzymanski** [comment]
It's worth noting that, as far as I can tell, there is no support for building ParseLiveQuery in any way outside of CocoaPods. I can't even build the library manually, which I would expect to work.

**Comment by dstarke** [comment]
Fixing this requires major changes to the way the library is built. Currently, building this library can only be done using CocoaPods, which maintains a lot of the build mechanics. Without it (or on a fresh checkout), the build doesn't work. For example, CocoaPods maintains the build phase script which checks to make sure `pod install` has been run and fails the build otherwise. That script can't be altered or removed because it will be restored the next time that `pod install` runs.

It seems like other projects use a combination of Carthage and Git submodules to make the dependencies available, and configure the Xcode project or workspace to correctly build the project without any additional tool requirements.

The dependencies are already included in this project as Git submodules, so the main change would be to set up the project and workspace to build without using CocoaPods.

To give a sense of what this might look like, I've made an attempt at this in a branch on a fork:

[universal-build branch of Workhood/ParseLiveQuery-iOS-OSX](/Workhood/ParseLiveQuery-iOS-OSX/tree/universal-build)

I'm happy to submit this back as a pull request. We've tested this by building with Xcode, by building from the command line, and by including it as a dependency with Carthage, and it seems to work, but there may be other build situations that we haven't tried, and I haven't fixed the example projects to work under this new build strategy.

I realize this is a dramatic change to how things are built, but in the current state without such changes, given what Apple has said about binary compatibility for frameworks and apps built with different versions of the compiler, the only safe workaround is to manually integrate by copying this project's sources into your project and adding this project's dependencies as dependencies of your project.

**Comment by JoeSzymanski** [comment]
I think that kind of change is exactly what I was expecting needed to be done. A pull request is probably a good starting point for getting this build process fixed.

**Comment by flovilmart** [comment]
Odd thing is that a local build with `carthage build --no-skip-current` is functional.

**Comment by JoeSzymanski** [comment]
I'm not certain that the `carthage build` command actually builds the Xcode project if there are pre-built binaries available. I previously tried `carthage update --no-use-binaries` and was unable to get a functional build working.

**Comment by dstarke** [comment]
I think `carthage build --no-skip-current` would have worked if you had previously run a `pod install` in your development environment. And Carthage may have appeared to work from other projects if you didn't force it to not use binaries, but that's not safe for Swift-based libraries. It didn't work for me on a fresh checkout, and I had the same experience as @JoeSzymanski attempting to use it in a dependent project, since I was forcing `--no-use-binaries`. (I would not have figured out what was going on without this thread, so thank you!)

I'll issue a pull request for my changes. I do want to point out that it will change the development environment considerably for anyone who works on this project, as CocoaPods would no longer be used to build, and the Git submodules need to be kept up to date correctly. In addition, my changes break the example projects, which either need to be changed to not use CocoaPods, or updated to use CocoaPods in a self-contained way. I expected both of these issues to be sticking points for accepting a pull request.

**Comment by flovilmart** [comment]
> , as CocoaPods would no longer be used to build, and the Git submodules need to be kept up to date correctly

I'm not sure that shift is really necessary, I'm confident we can have a simple build script that would yield a proper library.

**Comment by flovilmart** [comment]
I don't think the full overhaul is needed just because the bolts lib version is 0.0.0 instead of 1.0.0.

**Comment by JoeSzymanski** [comment]
@flovilmart The version number of bolts library is a symptom of the larger problem around using a pre-built library. Swift expressly forbids using pre-built binaries.

In addition, the library currently requires building via cocoapods, which means that the only way to integrate currently is also via cocoapods. Neither Carthage nor directly including the project as a dependent work without the full cocoapods integration being in place.

I think the best way to move forward is to try to remove the requirement of cocoapods at some point, since that puts some heavy limits on how the library can be integrated.

**Comment by flovilmart** [comment]
> Swift expressly forbids using pre-built binaries.

not sure what you mean by that, we use them all the time through carthage and github releases.

>  Neither Carthage nor directly including the project as a dependent work without the full cocoapods integration being in place.

There is the Cartfile that should provide the dependencies, independent of cocoapods, Bolts is Carthage compatible.

**Comment by dstarke** [comment]
The binary format for Swift frameworks is not stable. It can change with every compiler release, so you shouldn't distribute Swift-based frameworks as binaries. There's no way to tell which compiler version built them. Up to now, it has seemed to usually work, but there's no guarantee, so it's a time bomb. There's a reference link for this above and more information available on the Swift mailing lists.

The Cartfile lists the dependencies, but Carthage depends on the project to build the framework. The current version of this project will not build if CocoaPods is not present and a developer has not run `pod install` on the checkout prior to the build, so when Carthage attempts to build this framework, it fails. A build phase could be added to perform this step, but that would mean that using this library would require the installation of CocoaPods.

**Comment by JoeSzymanski** [comment]
@flovilmart For additional clarification, see the link I posted previously: https://forums.developer.apple.com/thread/66852

Swift is not ABI stable, and Apple expressly indicates that distribution of Swift frameworks should be done via source and not via pre-built binaries. At the same time, building the framework should not have any requirement on Cocoapods (though I understand that, this having been a hacked project originally, Cocoapods was the fastest way to get things functional at the start).

In addition, the current build process requires full integration of Cocoapods, which means our build now has hundreds of additional files to build. While it's possible for frameworks to be shipped via Cocoapods as binaries, most don't support it, leaving little possibility of trying to integrate large projects (like Parse) as binaries.

I still agree with @dstarke that the best way to move forward is to look into updating the build logic to no longer require Cocoapods to build the framework at all. That would allow much safer distribution of the source and make it easier for any third parties to integrate without requiring everyone else to integrate Cocoapods. This would solve multiple problems, including allowing usage of binaries directly where preferred and allowing local builds more easily without requiring third party utilities.

**Comment by flovilmart** [comment]
I don't disagree with that standpoint, but for now, but still Cocoapods has to be supported fully, and right now a carthage compatible build is incompatible with CP, because they both need different versions of SocketRocket (Carthage on master +, and CP on 0.5.1 (because 0.6 is not release))
SocketRocket doesn't build correctly at version 0.5.1 with Carthage, and the SR Api changes between those 2 versions.

It's impossible to declare a dependency with CP that is on a branch in the Podspec.

I'm not against moving forward but it is obvious with the current state of affairs that it either Carthage OR Cocoapods (because of SocketRocket). Therefore, Carthage support will come when SocketRocket releases a new version of it's framework.

**Comment by dstarke** [comment]
@JoeSzymanski It looks like @flovilmart has taken my changes into a branch ('carthage-support'), so I'd recommend temporarily pointing your Cartfile at that branch rather than a release tag until there's a new release with universal support.

**Comment by flovilmart** [comment]
At least on that branch, the socket rocket Version is the same for CP AND Carthage

**Comment by dstarke** [comment]
@JoeSzymanski version 2.0 was released today and should resolve all of these issues.

**Comment by flovilmart** [comment]
Closing now as it should be 💯 with carthage support.

**Comment by cubycode** [comment]
Hi there, is it possible to get the Parse LiveQuery framework via Carthage only, no Pods?
I've tried to set `github "ParseLiveQuery-iOS-OSX"` in my Cartfile, but after running `carthage update` the Terminal prints this out:
`Parse error: invalid GitHub repository identifier "ParseLiveQuery-iOS-OSX"
`
Thanks :)

**Comment by flovilmart** [comment]
You have to specify the full repository in your dependency:

`github “parse-community/ParseLiveQuery-iOS-OSX”`

**Comment by cubycode** [comment]
@flovimart thanks so much!
