### ISSUE TITLE
Is live query not support "Array of PFObject or PFUser"?

### ISSUE THREAD

**Issue by ShawnBaek** [parse-community/ParseLiveQuery-iOS-OSX#91]
I had trying to constraint query like this.

equalTo : PFObject or PFUser

but It is not working because JSON errors.

 

var newsLiveQuery: PFQuery<News> {
        return News.query()?
            .whereKeyExists("objectId")
            .includeKeys(["notiBy", "postObj", "notiTo", "notiArray"])
//            .whereKey("notiArray", equalTo: PFUser.current()!)
//            .whereKey("notiTo", equalTo: PFUser.current()!)
            .order(byDescending: "createdAt")
            as! PFQuery<News>
    }

**Comment by rjdlee** [comment]
I'm pretty sure live query only supports NSValue data types.

**Comment by flovilmart** [comment]
Can you try with the newly released 2.0.0, we've improved encoding/decoding of all objects

**Comment by rjdlee** [comment]
@flovilmart Does that mean it 2.0.0 supports relational object references? I've been using object IDs to store references.

**Comment by flovilmart** [comment]
I didn't test but the object encoder/decoder is the same as the Parse SDK now, not sure how it's handled server side

**Comment by ananfang** [comment]
@flovilmart 
@rjdlee 
Based on my project, even using 2.0.0, the issue is still there.
equalTo: (objectId) works.
equalTo: (object, e.g. User) doesn't work.

**-UPDATED-**
My alternative solution is using key path for whereKey:
(e.g.) live query for the creator of the story is me.
storyQuery.whereKey("creator.objectId", equalTo: (myUserId) )
That works fine.
